"""init

Revision ID: 8ff892d9bfae
Revises: 
Create Date: 2026-02-26 21:31:26.677816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff892d9bfae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_sagas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('order_cancelled', sa.Boolean(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('payment_cancelled', sa.Boolean(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=True),
    sa.Column('reservation_cancelled', sa.Boolean(), nullable=False),
    sa.Column('delivery_id', sa.UUID(), nullable=True),
    sa.Column('delivery_cancelled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('UNFINISHED', 'CANCELLED', 'COMPLETED', name='sagastatus'), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_sagas')
    # ### end Alembic commands ###
